// Enhanced Behavioral Model Constants
export const LEARNING_CONSTANTS = {
  ADAPTIVE_LEARNING: {
    BASE_RATE: 0.1,
    MIN_RATE: 0.01,
    MAX_RATE: 0.3,
    CONFIDENCE_THRESHOLD: 0.7,
    ADAPTATION_FACTOR: 0.05
  },
  FEEDBACK_WEIGHTS: {
    COMPLETED: 1.0,
    ENGAGED: 0.6,
    IGNORED: -0.3,
    FRUSTRATED: -0.8,
    CONTEXT_MULTIPLIER: 0.2
  },
  MEMORY_LIMITS: {
    INTERACTIONS_PER_USER: 200,
    PATTERN_HISTORY_DAYS: 30,
    MIN_SAMPLES_FOR_PREDICTION: 5
  },
  RISK_THRESHOLDS: {
    PROCRASTINATION: {
      HIGH_DAYS: 2.0,
      MEDIUM_DAYS: 1.0,
      ACTIVITY_HOURS: 4.0
    },
    PERSONALIZATION: {
      ADAPTATION_SAMPLES: 10,
      CONFIDENCE_DECAY: 0.95
    }
  }
} as const;